import './globals.css';
import SessionProvider from './SessionProvider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang='en'>
            <body>
                <SessionProvider>
                    <div className='flex flex-col justify-center items-center p-4 h-screen space-y-4 bg-white shadow-sm'>
                        <h1 className='font-bold text-3xl'>Next 13 with Next Auth</h1>
                        {children}
                    </div>
                </SessionProvider>
            </body>
        </html>
    );
}
